name: bump version and publish

permissions:
  packages: write
  contents: read

on:
  push:
    branches:
      - master
      - npm-pkg

jobs:
  bump-version-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
          scope: '@sportvot'

      - name: install deps
        run: npm ci

      - run: npm run publish-package
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
